# Generated by Django 5.2 on 2025-05-18 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_post_image_alter_post_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
